version: 0.2
        
phases:
  install:
    runtime-versions:
      python: 3.10 # IT WILL INSTALL PYTHON ON THE ENVIRONMENT (EC2)
    commands:
      - echo === INSTALL CFN-LINT ===
      - pip3 install cfn-lint
    
  pre_build:
    commands:
      - echo === CHECKING FOR PYTHON INSTALL ===
      - python3 --version
      - echo === CHECKING FOR AWSCLI INSTALL ===
      - aws --version
      - echo === CHECKING FOR CFN-LINT ===
      - cfn-lint --version
    
  build:
    commands:
      - echo === TEST OUR TEMPLATE ===
      - cfn-lint 1-ec2-user-data.yaml
      - echo *** TEMPLATE TEST COMPLETED ***
      - echo === BUILD OUR TEMPLATE ===
      - aws cloudformation package --template-file 1-ec2-user-data.yaml --s3-bucket my-deployed-artifacts-bucket --output-template-file build-artifact-template.yaml
    
  post_build:
    commands:
      - echo === ACTION TO TAKE WHEN BUILD IS COMPLETE ===
      - echo Build completed at `date`...
    
artifacts:
  files:
    - build-artifact-template.yaml # Creates the zip file (artitact) ---> in the deploy stage
